### ISSUE TITLE
Social Media JSON bug? 

### ISSUE THREAD

**Issue by Tmpod** [Snuggle/hypixel.py#11]
Hey!
I'm currently doing a Discord bot for my server and I need to detect which Discord account is connected to a player if there is one. I used the advanced example to test if the wrapper was working properly and I don't get any twitter nor any other social media account detected. I've double checked if my name was spelled properly and I went to plancke.io to see if it was an API problem. Can you please confirm if there's actually a bug or not? Because the thing is you are grabbing a json parameter called 'socialMedia' which includes 'links' before the actual 'DISCORD' or 'TWITTER' keys. You might have overlooked it or it might have changed since you did the example.

Best regards

**Comment by Snuggle** [comment]
_Snuggle's API Response_
![image](https://user-images.githubusercontent.com/26250962/38717404-a5a2d2b0-3ede-11e8-8f80-0a32975a1cef.png)

The more complicated example is supposed to get the key above from the API, but there's since been a massive social media update that added `Links` and renamed Beam to Mixer, added Hypixel forums and Discord. I'm guessing the old keys (Not under `Links`) aren't used anymore, could you confirm that?

If so, I'd be more than happy with having the example updated to use the new format. c:

**Comment by Tmpod** [comment]
Yeah I exactly. Now everything is under 'links'. I don't really know how to work with JSON in python or I would do a pull request.
Thanks

**Comment by Snuggle** [comment]
Ah, no worries! The commit earlier should've fixed it! c:
Thank you for making an issue, I wouldn't have realised. :yum:
